language: python
os:
  - linux
  - osx
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install:
    - "python setup.py develop"
    - "pip install -e  '.[tests]'"
    # code coverage tool
    - "pip install coveralls"
    # manually install wheel for deployment
    - "pip install wheel"
script:
    - "py.test --verbose --capture=no --showlocals --cov tests"
    - "pylama"
after_success:
    - coveralls
