language: python
sudo: false
os:
  - linux
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
# blocklist branches
branches:
  except:
  - requires-io-master
install:
  - "pip install -r requirements-test.txt"
  - "python setup.py develop"
  - "pip install -e  '.[tests]'"
  # code coverage tool
  - "pip install coveralls"
  # manually install wheel for deployment
  - "pip install wheel"
script:
    - "py.test --verbose --capture=no --showlocals --cov tests"
    - "pylama"
after_success:
    - coveralls

deploy:
    provider: pypi
    user: fizyk
    password:
        secure: OyYYYSlg/kWhaZXm5Ll9P8RdLDyBIUac7cI2V5q+U4QWo9lSgJQC7HOTiaIJx8suBgDEZji1Ne7Klvg0bgDTaI6U1E/PS4SZdFhx/x4U4HgRLkdNRSC8i+OdOUVs2kEtixcoU2PDISJ+dN6Rs0Ih4vxJ5gkiqGEuQlalyVH010U=
    on:
        tags: true
        all_branches: true
        repo: ClearcodeHQ/pytest-repeater
    distributions: "sdist bdist_wheel"
